package com.app.fooddiary;


import javafx.fxml.FXMLLoader;
import javafx.scene.layout.Pane;
import org.json.simple.JSONObject;
import pah9qdbulletjournal.Page;
import pah9qdbulletjournal.Page;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FoodDiary.java
//  @ Date : 4/17/2016
//  @ Author : 
//
//
public class FoodDiary extends Page {

    @Override
    public FXMLLoader getFXMLLoader() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public JSONObject convertToJson() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void parseJson() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
