package com.app.taskpage;

//

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.SimpleBooleanProperty;
import org.json.simple.JSONObject;
import pah9qdbulletjournal.JSONAble;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Task.java
//  @ Date : 4/17/2016
//  @ Author : 
//
//
public class Task implements JSONAble{
    private String name;
    
    private String description;
    
    private transient BooleanProperty completed = new SimpleBooleanProperty();

    public Task() {
        
    }
    
    public Task(String name) {
        this();
        this.name = name;
    }
    
    public Task(String name, String description) {
        this(name);
        this.description = description;
    }
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getDescription() {
        return description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public BooleanProperty getCompleted() {
        return completed;
    }
    
    public void setCompleted(BooleanProperty completed) {
        this.completed = completed;
    }

    @Override
    public JSONObject convertToJson() {
        JSONObject obj = new JSONObject();
        obj.put("name", name);
        obj.put("description", description);
        obj.put("completed", completed.getValue());
        
        return obj;
    }

    @Override
    public void parseJson(JSONObject jsonObject) {
        name = (String) jsonObject.get("name");
        description = (String) jsonObject.get("description");
        completed.setValue((Boolean) jsonObject.get("completed"));
    }
}
