package pah9qdbulletjournal;


import pah9qdbulletjournal.Page;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FoodDiary.java
//  @ Date : 4/17/2016
//  @ Author : 
//
//
public class FoodDiary extends Page {
}
