package pah9qdbulletjournal;

import java.util.ArrayList;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Journal.java
//  @ Date : 4/17/2016
//  @ Author : 
//
//
public class Journal {
    private ArrayList<Page> pages;
    private static ArrayList<Journal> journals;
    public ArrayList<Page> getPages() {
        return pages;
    }
    
    public void addPage(Page page) {
        pages.add(page);
    }
    
    public void removePage(Page page) {
        pages.remove(page);
    }
    
    public void saveJournalToFile() {
    }
    
    public void loadJournalFromFile() {
    }
}
