package pah9qdbulletjournal;

import java.util.ArrayList;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.control.TreeItem;
import javafx.scene.control.TitledPane;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Journal.java
//  @ Date : 4/17/2016
//  @ Author : 
//
//
public class Journal{
    private String name;
    private String description;
    private ObservableList<Page> pages = FXCollections.observableArrayList();
    private static ArrayList<Journal> journals = new ArrayList<>();
    
    private TitledPane titledPane;
    
    public Journal() {
        journals.add(this);
    }
    
    public Journal(String name) {
        this();
        setName(name);
    }
    
    public Journal(String name, String description) {
        this(name);
        setDescription(description);
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getName() {
        return name;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getDescription() {
        return description;
    }
    
    public ObservableList<Page> getPages() {
        return pages;
    }
    
    public void addPage(Page page) {
        if(page != null) {
            if(!pages.contains(page)) {
                pages.add(page);
            }
            if(page.getBelongsToJournal() != this) {
                page.setBelongsToJournal(this);
            }
        } else {
            System.out.println("Error in addPage of Journal " + getName());
        }
        
        
    }
    
    public void removePage(Page page) {
        pages.remove(page);
    }
    
    public void saveJournalToFile() {
        
    }
    
    public void loadJournalFromFile() {
    }
    
    public static ArrayList<Journal> getJournals() {
        return journals;
    }
    
    public static void addJournal(Journal journal) {
        Journal.journals.add(journal);
    }

    public TitledPane getTitledPane() {
        return titledPane;
    }

    public void setTitledPane(TitledPane titledPane) {
        this.titledPane = titledPane;
    }
}
