package pah9qdbulletjournal;


import javafx.scene.layout.Pane;
import pah9qdbulletjournal.Page;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MonthCalendar.java
//  @ Date : 4/17/2016
//  @ Author : 
//
//




public class MonthCalendar extends Page {

    @Override
    public Pane getFXPane() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Pane setFXPane() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
