package pah9qdbulletjournal;


import pah9qdbulletjournal.Page;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MonthCalendar.java
//  @ Date : 4/17/2016
//  @ Author : 
//
//




public class MonthCalendar extends Page {
}
