package pah9qdbulletjournal;

//

import javafx.scene.layout.Pane;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Page.java
//  @ Date : 4/17/2016
//  @ Author : 
//
//
public abstract class Page{
    private String name;
    private String description;
    private Journal belongsToJournal;
    private Pane fxPane;
    
    public Page() {
    }
    
    public Page(String name) {
        setName(name);
    }
    
    public Page(String name, String description) {
        this(name);
        setDescription(description);
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getName() {
        return name;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getDescription() {
        return description;
    }
    
    public Journal getBelongsToJournal() {
        return belongsToJournal;
    }
    
    // A Page must belong to a Journal. Therefore, the only way to remove a Page
    // from a journal is to set it a different journal.
    public void setBelongsToJournal(Journal belongsToJournal) {
        if(this.belongsToJournal != null) {
            belongsToJournal.removePage(this);
        }
        if(!belongsToJournal.getPages().contains(this)) {
            belongsToJournal.addPage(this);
        }
        this.belongsToJournal = belongsToJournal;
    }
    
    public abstract Pane getFXPane();
    public abstract Pane setFXPane();
}
