package pah9qdbulletjournal;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Page.java
//  @ Date : 4/17/2016
//  @ Author : 
//
//
public abstract class Page{
    private String name;
    private String description;
    private Journal myJournal;
    
    public Page() {
    }
    
    public Page(String name) {
        setName(name);
    }
    
    public Page(String name, String description) {
        this(name);
        setDescription(description);
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getName() {
        return name;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getDescription() {
        return description;
    }
    
    public void addToJournal(Journal journal) {
        journal.addPage(this);
        myJournal = journal;
    }
    
    public void removeFromJournal(Journal journal) {
        journal.removePage(this);
    }
    
    public Journal getMyJournal() {
        return myJournal;
    }
    
    public void setMyJournal(Journal myJournal) {
        this.myJournal = myJournal;
    }
}
