package pah9qdbulletjournal;
//
//  Generated by StarUML(tm) Java Add-In

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.fxml.FXMLLoader;
import javafx.scene.layout.Pane;

//
//  @ Project : Untitled
//  @ File Name : TaskPage.java
//  @ Date : 4/17/2016
//  @ Author : 
//
//

public class TaskPage extends Page{
    private ArrayList<Task> tasks;
    
    public TaskPage() {
        
    }
    
    public TaskPage(String name) {
        super(name);
    }
    
    public TaskPage(String name, String description) {
        super(name, description);
    }
    
    public void addTask(Task task) {
        tasks.add(task);
    }
    
    public void removeTask(String task) {
        tasks.remove(task);
    }

    @Override
    public Pane getFXPane() {
        try {
            return (Pane)FXMLLoader.load(getClass().getResource("TaskPageUI.fxml"));
        } catch (IOException ex) {
            Logger.getLogger(TaskPage.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }

    @Override
    public Pane setFXPane() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
