package pah9qdbulletjournal;
//
//  Generated by StarUML(tm) Java Add-In

import java.util.ArrayList;

//
//  @ Project : Untitled
//  @ File Name : TaskPage.java
//  @ Date : 4/17/2016
//  @ Author : 
//
//




public class TaskPage extends Page{
    private ArrayList<Task> tasks;
    public void addTask(String name) {
        tasks.add(new Task(name));
    }
    
    public void removeTask(String task) {
    }
}
