package pah9qdbulletjournal;
//
//  Generated by StarUML(tm) Java Add-In

import java.util.ArrayList;

//
//  @ Project : Untitled
//  @ File Name : TaskPage.java
//  @ Date : 4/17/2016
//  @ Author : 
//
//

public class TaskPage extends Page{
    private ArrayList<Task> tasks;
    
    public TaskPage() {
        
    }
    
    public TaskPage(String name) {
        super(name);
    }
    
    public TaskPage(String name, String description) {
        super(name, description);
    }
    
    public void addTask(String name) {
        tasks.add(new Task(name));
    }
    
    public void removeTask(String task) {
    }
    
//    CheckBoxTreeItem<String> treeItemRoot = new CheckBoxTreeItem<>("Root");
//        
////        CheckBoxTreeItem<String> nodeItemA = new CheckBoxTreeItem<>("Item A");
////        CheckBoxTreeItem<String> nodeItemB = new CheckBoxTreeItem<>("Item B");
////        CheckBoxTreeItem<String> nodeItemC = new CheckBoxTreeItem<>("Item C");
////        treeItemRoot.getChildren().addAll(nodeItemA, nodeItemB, nodeItemC);
////         
////        CheckBoxTreeItem<String> nodeItemA1 = new CheckBoxTreeItem<>("Item A1");
////        CheckBoxTreeItem<String> nodeItemA2 = new CheckBoxTreeItem<>("Item A2");
////        CheckBoxTreeItem<String> nodeItemA3 = new CheckBoxTreeItem<>("Item A3");
////        nodeItemA.getChildren().addAll(nodeItemA1, nodeItemA2, nodeItemA3);
//        
//        journalList.setCellFactory(CheckBoxTreeCell.<String>forTreeView());    
//        for (int i = 0; i < 8; i++) {
//            final CheckBoxTreeItem<String> checkBoxTreeItem = 
//                new CheckBoxTreeItem<>("Sample" + (i+1));
//                    treeItemRoot.getChildren().add(checkBoxTreeItem);   
//        }
//
//        journalList.setRoot(treeItemRoot);
//        journalList.setEditable(true);
}
